package main

import (
	"bufio"
	"bytes"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

var safeCodexBaseKeys = map[string]bool{
	"model_provider":                    true,
	"model_providers":                   true,
	"model_catalog_json":                true,
	"openai_base_url":                   true,
	"chatgpt_base_url":                  true,
	"oss_provider":                      true,
	"experimental_realtime_ws_base_url": true,
}

func hostCodexHome() (string, error) {
	if home := strings.TrimSpace(os.Getenv("CODEX_HOME")); home != "" {
		return home, nil
	}
	userHome, err := os.UserHomeDir()
	if err != nil {
		return "", err
	}
	return filepath.Join(userHome, ".codex"), nil
}

func hostCodexBaseConfigPath() (string, error) {
	home, err := hostCodexHome()
	if err != nil {
		return "", err
	}
	return filepath.Join(home, "config.toml"), nil
}

func installWorkerBaseConfig(baseSource, workerHome, worktree string) error {
	workerHome = strings.TrimSpace(workerHome)
	worktree = strings.TrimSpace(worktree)
	if workerHome == "" || worktree == "" {
		return errors.New("worker CODEX_HOME or worktree missing")
	}
	if err := os.MkdirAll(workerHome, 0o700); err != nil {
		return err
	}

	var source []byte
	if strings.TrimSpace(baseSource) != "" {
		data, err := os.ReadFile(baseSource)
		if err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("read host Codex base config: %w", err)
		}
		if err == nil {
			source = data
		}
	}

	generated, err := sanitizeCodexBaseConfig(source, worktree)
	if err != nil {
		return err
	}
	return writePrivateFileAtomic(filepath.Join(workerHome, "config.toml"), generated)
}

func sanitizeCodexBaseConfig(source []byte, worktree string) ([]byte, error) {
	if strings.ContainsAny(worktree, "\r\n") {
		return nil, errors.New("worktree path contains unsupported control characters")
	}

	var out bytes.Buffer
	out.WriteString("# Generated by CDDM. Host integrations are intentionally filtered.\n")

	scanner := bufio.NewScanner(bytes.NewReader(source))
	scanner.Buffer(make([]byte, 64*1024), 4*1024*1024)
	inAllowedSection := false
	for scanner.Scan() {
		line := scanner.Text()
		trimmed := strings.TrimSpace(line)
		if isTOMLSectionHeader(trimmed) {
			inAllowedSection = isModelProviderSection(trimmed)
			if inAllowedSection {
				out.WriteString("\n")
				out.WriteString(line)
				out.WriteString("\n")
			}
			continue
		}
		if inAllowedSection {
			out.WriteString(line)
			out.WriteString("\n")
			continue
		}
		if key, ok := topLevelTOMLKey(trimmed); ok && safeCodexBaseKeys[key] {
			out.WriteString(line)
			out.WriteString("\n")
		}
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("scan host Codex base config: %w", err)
	}

	out.WriteString("\n[projects.")
	out.WriteString(tomlQuotedString(worktree))
	out.WriteString("]\ntrust_level = \"trusted\"\n")
	return out.Bytes(), nil
}

func isTOMLSectionHeader(line string) bool {
	return strings.HasPrefix(line, "[") && strings.HasSuffix(line, "]")
}

func isModelProviderSection(header string) bool {
	inner := strings.TrimSpace(strings.Trim(header, "[]"))
	return inner == "model_providers" || strings.HasPrefix(inner, "model_providers.")
}

func topLevelTOMLKey(line string) (string, bool) {
	if line == "" || strings.HasPrefix(line, "#") {
		return "", false
	}
	idx := strings.IndexByte(line, '=')
	if idx <= 0 {
		return "", false
	}
	key := strings.TrimSpace(line[:idx])
	if key == "" || strings.ContainsAny(key, " .\t") {
		return "", false
	}
	return key, true
}

func tomlQuotedString(value string) string {
	replacer := strings.NewReplacer("\\", "\\\\", "\"", "\\\"")
	return "\"" + replacer.Replace(value) + "\""
}

func writePrivateFileAtomic(path string, data []byte) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o700); err != nil {
		return err
	}
	tmp, err := os.CreateTemp(filepath.Dir(path), ".cddm-config-*.tmp")
	if err != nil {
		return err
	}
	name := tmp.Name()
	defer os.Remove(name)
	if err := tmp.Chmod(0o600); err != nil {
		_ = tmp.Close()
		return err
	}
	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Sync(); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(name, path)
}
